### ISSUE TITLE
Target Language

### ISSUE THREAD

**Issue by venomousraid** [Fabrice-Deshayes-aka-Xtream/srt-translator#1]
Hello, although I changed the target language for translation from config.py, it only translates to english.

**Comment by Fabrice-Deshayes-aka-Xtream** [comment]
Hello. 

Here are the authorized values for target language as documented on deepl API https://www.deepl.com/fr/docs-api/translate-text/translate-text

```
BG - Bulgarian
CS - Czech
DA - Danish
DE - German
EL - Greek
EN - English (unspecified variant for backward compatibility; please select EN-GB or EN-US instead)
EN-GB - English (British)
EN-US - English (American)
ES - Spanish
ET - Estonian
FI - Finnish
FR - French
HU - Hungarian
ID - Indonesian
IT - Italian
JA - Japanese
KO - Korean
LT - Lithuanian
LV - Latvian
NB - Norwegian (Bokmål)
NL - Dutch
PL - Polish
PT - Portuguese (unspecified variant for backward compatibility; please select PT-BR or PT-PT instead)
PT-BR - Portuguese (Brazilian)
PT-PT - Portuguese (all Portuguese varieties excluding Brazilian Portuguese)
RO - Romanian
RU - Russian
SK - Slovak
SL - Slovenian
SV - Swedish
TR - Turkish
UK - Ukrainian
ZH - Chinese (simplified)
```

Could you copy/past me your modified config.py file so I can check?

Regards.

**Comment by Fabrice-Deshayes-aka-Xtream** [comment]
Just to be sure, the result of the translation can be found in the "result" folder, if your original file is in English, it is renamed with suffix "_EN" and move to "done" folder.  So please, confirm that you've checked the "result" folder and not the "done" one please.

**Comment by Martyprod** [comment]
> Hello, although I changed the target language for translation from config.py, it only translates to english.

Hi, just to confirm you that the app work well, i use it to translate for English to French. check that you didn't do a mistake, or maybe you missed the to do / planned / result / done, folder ?

**Comment by Fabrice-Deshayes-aka-Xtream** [comment]
can't reproduce, no news since four months. I close this issue.
